/*
 * Product Catalog Management
 *
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 20.5 - March 2021  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 4.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A collection of Product Offerings, intended for a specific DistributionChannel, enhanced with additional information such as SLA parameters, invoicing and shipping details Skipped properties: id,href,lastUpdate,@type,@baseType
type CatalogUpdate struct {

	// Indicates if the catalog is a product, service or resource catalog
	CatalogType string `json:"catalogType,omitempty"`

	// Description of this catalog
	Description string `json:"description,omitempty"`

	// Used to indicate the current lifecycle status
	LifecycleStatus string `json:"lifecycleStatus,omitempty"`

	// Name of the catalog
	Name string `json:"name,omitempty"`

	// Catalog version
	Version string `json:"version,omitempty"`

	// List of root categories contained in this catalog
	Category []CategoryRef `json:"category,omitempty"`

	// List of parties involved in this catalog
	RelatedParty []RelatedParty `json:"relatedParty,omitempty"`

	// The period for which the catalog is valid
	ValidFor *TimePeriod `json:"validFor,omitempty"`

	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`
}
