/*
 * Product Catalog Management
 *
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 20.5 - March 2021  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 4.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Is an amount, usually of money, that modifies the price charged for an order item.
type PopAlteration struct {

	// unique identifier
	Id string `json:"id,omitempty"`

	// Hyperlink reference
	Href string `json:"href,omitempty"`

	// A narrative that explains in detail the semantics of this order item price alteration
	Description string `json:"description,omitempty"`

	// Name given to this price alteration
	Name string `json:"name,omitempty"`

	// A category that describes the price such as recurring, one time and usage.
	PriceType string `json:"priceType"`

	// Priority level for applying this alteration among all the defined alterations on the order item price
	Priority int32 `json:"priority,omitempty"`

	// Could be month, week...
	RecurringChargePeriod string `json:"recurringChargePeriod,omitempty"`

	// The period for which the productOfferingPriceAlteration is applicable
	ApplicationDuration *Duration `json:"applicationDuration,omitempty"`

	Price *ProductPriceValue `json:"price"`

	// A number and unit representing denominator of an alteration rate. For example, for a data discount rate of $1 per 20 GB usage, the amount of unitOfMeasure will be 20 with units as GB.
	UnitOfMeasure *Quantity `json:"unitOfMeasure,omitempty"`

	// The period for which this productOfferingPriceAlteration is valid
	ValidFor *TimePeriod `json:"validFor,omitempty"`

	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`

	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`

	// When sub-classing, this defines the sub-class Extensible name
	Type_ string `json:"@type,omitempty"`
}
