/*
 * Product Catalog Management
 *
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 20.5 - March 2021  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 4.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Provides all amounts (tax included, duty free, tax rate), used currency and percentage to apply for Price Alteration.
type ProductPriceValue struct {

	// Percentage to apply for ProdOfferPriceAlteration
	Percentage float32 `json:"percentage,omitempty"`

	// Tax category
	TaxCategory string `json:"taxCategory,omitempty"`

	// Tax rate
	TaxRate float32 `json:"taxRate,omitempty"`

	// All taxes excluded amount (expressed in the given currency)
	DutyFreeAmount *Money `json:"dutyFreeAmount,omitempty"`

	// All taxes included amount (expressed in the given currency)
	TaxIncludedAmount *Money `json:"taxIncludedAmount,omitempty"`

	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`

	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`

	// When sub-classing, this defines the sub-class Extensible name
	Type_ string `json:"@type,omitempty"`
}
