/*
 * Product Catalog Management
 *
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 20.5 - March 2021  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 4.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents a task used to export resources to a file Skipped properties: id,href
type ExportJobCreate struct {

	// Data at which the job was completed
	CompletionDate time.Time `json:"completionDate,omitempty"`

	// The format of the exported data
	ContentType string `json:"contentType,omitempty"`

	// Date at which the job was created
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Reason for failure
	ErrorLog string `json:"errorLog,omitempty"`

	// URL of the root resource acting as the source for streaming content to the file specified by the export job
	Path string `json:"path,omitempty"`

	// Used to scope the exported data
	Query string `json:"query,omitempty"`

	// URL of the file containing the data to be exported
	Url string `json:"url"`

	// Status of the export job (not started, running, succeeded, failed)
	Status *JobStateType `json:"status,omitempty"`

	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`

	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`

	// When sub-classing, this defines the sub-class Extensible name
	Type_ string `json:"@type,omitempty"`
}
